name             'streamtools'
maintainer       'Jacqui Maher, The New York Times'
maintainer_email 'jacqui.maher@nytimes.com'
license          'Apache'
description      'Installs/configures streamtools, optionally sets up reverse proxy for nginx'
depends         'apt'
depends         'build-essential'
depends         'git'
depends       'golang'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.3.0'
